### ISSUE TITLE
Failed to build as standalone package

### ISSUE THREAD

**Issue by Karlson2k** [xbmc/screensaver.pingpong#26]
See https://github.com/xbmc/screensaver.greynetic/issues/19 and https://github.com/xbmc/screensaver.asteroids/issues/24
Same error

**Comment by AlwinEsch** [comment]
Fixed with https://github.com/xbmc/screensaver.pingpong/pull/29 (Leia) and https://github.com/xbmc/screensaver.pingpong/pull/28 (Matrix).

Stupid that they have removed install from the GLM.

Also on all other addons where use GLM becomes the `Findglm.cmake` added to have this fixed.

**Comment by Karlson2k** [comment]
I fixed GLM package for Gentoo.
Maybe other distribution will adapt to exotic GLM's way of installation.
